{
 "title": "iDRAC - Host Stats",
 "description": "SNMP Based Dashboard to Monitor Dell Hosts via iDRAC - by ilovepancakes95",
 "tags": [
  "idrac",
  "telegraf",
  "snmp"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "idrac_host",
    "label": "iDRAC Host",
    "query": "SHOW TAG VALUES FROM \"idrac-hosts\" WITH KEY=\"system-name\""
   }
  ]
 },
 "panels": [
  { "title": "iDRAC Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "idrac-url" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"bios-version\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"system-name\" LIMIT 1",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-model" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Status Map",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "[[tag_system-name]]",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "# of iDRACs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values cardinality from \"idrac-hosts\" with key = \"system-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$idrac_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "idrac_host" },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Watts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "System Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "CPU 2 Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu2-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "PSU Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "psu-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CMOS Battery",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cmos-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAID Battery",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "raid-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "BIOS Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "storage-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "memory-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Thermal Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Intrusion",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "intrusion-sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Status",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-predictivefail" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Log Entries",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 9, "x": 7, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"log-dates\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"log-number\" LIMIT 1",
     "select": [
      [
       { "params": [ "log-dates" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-entry" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-severity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inlet Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Exhaust Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "exhaust-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "RPM" }
   ],
   "targets": [
    {
     "alias": "Fan 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan1-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan2-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan3-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan4-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan5-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan6-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-vendor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-current_mac" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  }
 ]
}