{
 "title": "Proxmox",
 "description": "Display data from the Proxmox host and hosted VM's and Containers.",
 "tags": [
  "proxmox",
  "hardware",
  "earth"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host WHERE object='nodes'"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "memory",
     "select": [
      [
       { "params": [ "swaptotal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Server CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Average (1 Minute)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "avg1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "dateTimeAsUSNoDateIfToday",
   "valueName": "last_time",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vmid" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT \"uptime\" AS \"uptime\", \"status\" AS \"Status\", \"host\" AS \"VMID\", \"freemem\" /maxmem AS \"Memory Usage\", \"cpu\" AS \"CPU Usage\" FROM \"system\" WHERE (\"object\" = 'qemu') AND $timeFilter GROUP BY \"vmid\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       { "params": [ "uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "host" ], "type": "field" },
       { "params": [ "VMID" ], "type": "alias" }
      ],
      [
       { "params": [ "freemem" ], "type": "field" },
       { "params": [ "/maxmem" ], "type": "math" },
       { "params": [ "Memory Usage" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "CPU Usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  {
   "title": "Running LXCs",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(uptime) AS \"uptime\" FROM \"system\" WHERE (\"object\" = 'lxc') AND (\"nodename\" =~ /^$server$/) AND time > (now() - 10m) AND uptime > 0 GROUP BY \"host\" limit 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       { "params": [ "uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Storage Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "local Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"used\") / last(\"total\") FROM \"system\" WHERE (\"host\" = 'local' AND \"nodename\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DataPool Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"used\") / last(\"total\") FROM \"system\" WHERE (\"host\" = 'local' AND \"nodename\" =~ /^earth$/) AND time >= now() - 3h GROUP BY time(2m) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "/\"total\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "DataPool" }
     ]
    }
   ]
  },
  {
   "title": "FlashPool Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"used\") /\"total\" FROM \"system\" WHERE (\"nodename\" =~ /^$server$/ AND \"host\" = 'DataPool') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "/\"total\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "FlashPool" }
     ]
    }
   ]
  },
  {
   "title": "RAIDPool_LVM Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"used\") /\"total\" FROM \"system\" WHERE (\"nodename\" =~ /^$server$/ AND \"host\" = 'DataPool') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "/\"total\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "RAIDPool_LVM" }
     ]
    }
   ]
  },
  {
   "title": "RAIDPool_Backups Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"used\") /\"total\" FROM \"system\" WHERE (\"nodename\" =~ /^$server$/ AND \"host\" = 'DataPool') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "/\"total\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "RAIDPool_Backups" }
     ]
    }
   ]
  },
  {
   "title": "RAIDPool_Templates Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"used\") /\"total\" FROM \"system\" WHERE (\"nodename\" =~ /^$server$/ AND \"host\" = 'DataPool') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "/\"total\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "RAIDPool_Templates" }
     ]
    }
   ]
  },
  { "title": "Memory And CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "CPU Usage",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "I/O Wait",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Load Average (1 Min)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "avg1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memused\")/mean(\"memtotal\") * 100 FROM \"memory\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"cpu\") FROM \"system\" WHERE (\"object\" = 'qemu') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LXC CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"cpu\") FROM \"system\" WHERE (\"object\" = 'lxc' AND \"nodename\" =~ /^$server$/) AND $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT (mean(\"mem\")/last(maxmem))*100 FROM \"system\" WHERE (\"object\" = 'qemu') AND (\"nodename\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  {
   "title": "LXC Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT (mean(\"mem\")/last(maxmem))*100 FROM \"system\" WHERE (\"object\" = 'lxc') AND (\"nodename\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "VMs I/O Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "diskread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LXCs I/O Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT derivative(mean(\"diskread\"), 1s) FROM \"system\" WHERE (\"object\" = 'lxc' AND \"nodename\" =~ /^$server$/) AND $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "diskread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs I/O Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT derivative(mean(\"diskwrite\"), 1s) FROM \"system\" WHERE \"object\" = 'qemu' AND (\"nodename\" =~ /^$server$/) AND $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "diskwrite" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "dianna" }
     ]
    }
   ]
  },
  {
   "title": "LXCs I/O Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "diskwrite" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "eno1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1" }
     ]
    },
    {
     "alias": "Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1" }
     ]
    }
   ]
  },
  {
   "title": "eno1 - VLAN 40",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1.40" }
     ]
    },
    {
     "alias": "Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1.40" }
     ]
    }
   ]
  },
  {
   "title": "vmbr0",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmbr0" }
     ]
    },
    {
     "alias": "Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmbr0" }
     ]
    }
   ]
  },
  {
   "title": "eno1 - VLAN 50",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(mean(\"receive\"), 10s) AS \"Rx\", non_negative_derivative(mean(\"receive\"), 10s) AS \"Tx\" FROM \"nics\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" = 'enp2s0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1.50" }
     ]
    },
    {
     "alias": "Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "select": [
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "eno1.50" }
     ]
    }
   ]
  },
  {
   "title": "VMs Traffic In",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  {
   "title": "LCXs Traffic In",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  },
  {
   "title": "VMs Traffic Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "qemu" }
     ]
    }
   ]
  },
  {
   "title": "LXCs Traffic Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  }
 ]
}