{
 "title": "Jira Summary",
 "description": "Shows Jira JVM and usage metrics",
 "tags": [
  "prometheus",
  "Atlassian"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Common Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Attachments",
   "type": "singlestat",
   "description": "Displays the current attachments size",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_total_attachment_size_gauge"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The uptime of the Java virtual machine in milliseconds",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "jvm_uptime_gauge" }
   ]
  },
  {
   "title": "Total Issues",
   "type": "singlestat",
   "description": "The total issues in JIRA",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_issues_gauge" }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jira_request_duration_on_path_sum[1m])) by (path)) / (sum(rate(jira_request_duration_on_path_count[1m])) by (path))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Login/Logout",
   "type": "graph",
   "description": "Login/Logout increases per 1 hour",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jira_user_login_count[1h]))",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(increase(jira_user_logout_count[1h]))",
     "legendFormat": "Logout"
    }
   ]
  },
  {
   "title": "Dashboards Views",
   "type": "graph",
   "description": "Views of all dashboards increases",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jira_dashboard_view_count[1h]))"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "All Users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_all_users_gauge" }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_active_users_gauge " }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_sessions_gauge" }
   ]
  },
  {
   "title": "Authorized  Sessions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_authorized_sessions_gauge" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"jira-exporter\"}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"jira-exporter\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"jira-exporter\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"jira-exporter\"}[1m])",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"jira-exporter\"}",
     "legendFormat": "{{ gc }}"
    }
   ]
  }
 ]
}