{
 "title": "Weather",
 "description": "Access current weather data for any location on Earth including over 200,000 cities!",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SHOW TAG VALUES FROM \"weather\" WITH KEY = \"country\""
   },
   {
    "name": "city",
    "label": "City",
    "query": "show tag values from \"weather\" with key = \"city\";"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$tag_city, $tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "alias": "$tag_city, $tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"wind_speed\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval), \"sys_country\", \"name\" fill(none)",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_city, $tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "$tag_city, $tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"main_pressure\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval), \"country\", \"name\" fill(none)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Current weather data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "Wind direction",
     "groupBy": [
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wind_degrees" ], "type": "field" },
       { "params": [ "Wind direction" ], "type": "alias" }
      ],
      [
       { "params": [ "weather_0_description" ], "type": "field" },
       { "params": [ "Weather condition" ], "type": "alias" }
      ],
      [
       { "params": [ "sunrise" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Sunrise time" ], "type": "alias" }
      ],
      [
       { "params": [ "sunset" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Sunset time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" },
      { "condition": "AND", "key": "forecast", "operator": "=", "value": "*" }
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_city, $tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "cloudiness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  { "title": "$city", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "city" },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"temperature\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"wind_speed\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"name\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wind_degrees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Weather condition",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "forecast" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" },
      { "condition": "AND", "key": "forecast", "operator": "=", "value": "3h" }
     ]
    }
   ]
  },
  {
   "title": "Sunrise time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "city" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "sunrise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "cloudiness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Sunset time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "sys_sunset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  }
 ]
}