scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'federate'
    honor_labels: true
    metrics_path: '/federate'

    params:
      match[]:
        - '{job=~".+"}'

    static_configs:
      - targets:
        - 'callisto.sol.milkyway:9090'

  - job_name: 'pihole'
    static_configs:
      - targets:
        - 'ganymede.sol.milkyway:9617'

  - job_name: 'jira'
    metrics_path: '/plugins/servlet/prometheus/metrics'
    static_configs:
      - targets:
        - 'ariel.sol.milkyway:8080'

  - job_name: 'confluence'
    metrics_path: '/plugins/servlet/prometheus/metrics'
    static_configs:
      - targets:
        - 'europa.sol.milkyway:8090'
