{
 "title": "Plex Summary",
 "description": "A Grafana dashboard for Varken",
 "tags": [
  "plex",
  "tautulli",
  "ombi",
  "radarr",
  "sonarr",
  "telegraf",
  "InfluxDB",
  "worldmap",
  "piechart",
  "varken"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Varken datasource", "query": "influxdb" },
   {
    "name": "movielibrary",
    "label": "Movie Library",
    "query": "SHOW TAG VALUES ON varken WITH KEY = \"section_name\" "
   },
   {
    "name": "tvlibrary",
    "label": "TV Library",
    "query": "SHOW TAG VALUES ON varken WITH KEY = \"section_name\""
   },
   {
    "name": "animelibrary",
    "label": "Anime Library",
    "query": "SHOW TAG VALUES ON varken WITH KEY = \"section_name\""
   },
   {
    "name": "audiobooklibrary",
    "label": "Audiobook Library",
    "query": "SHOW TAG VALUES ON varken WITH KEY = \"section_name\""
   },
   {
    "name": "musiclibrary",
    "label": "Music Library",
    "query": "SHOW TAG VALUES ON varken WITH KEY = \"section_name\" "
   }
  ]
 },
 "panels": [
  { "title": "Library Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 1, "y": 1 },
   "content": "<font size=6><center> Movies </center></font>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "content": "<font size=6><center> TV </center></font>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "content": "<font size=6><center> Anime </center></font>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "content": "<font size=6><center> Music </center></font>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "content": "<font size=6><center> Audiobooks </center></font>"
  },
  {
   "title": "$movielibrary",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 1, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT \"total\" FROM \"Tautulli\" WHERE (\"section_name\" = 'Filmer') AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=~", "value": "/^$movielibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Shows",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_type", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$animelibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Songs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "tracks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$musiclibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Audiobooks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "albums" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$audiobooklibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Seasons",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Shows",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$animelibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Artists",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_type", "operator": "=", "value": "artist" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$musiclibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Tracks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 5 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "tracks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$audiobooklibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seasons",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Anime" }
     ]
    }
   ]
  },
  {
   "title": "Albums",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "albums" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Music" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$musiclibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Authors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$audiobooklibrary$/" }
     ]
    }
   ]
  },
  { "title": "Streaming Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "$container - RAM usage",
   "type": "graph",
   "description": "Thresholds are 1 GiB, 2 GiB, 4 GiB",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "$host - Download",
   "type": "singlestat",
   "description": "Thresholds are 10 mbit,50 mbit,100 mbit",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 10 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "OutBound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "$host - Upload",
   "type": "singlestat",
   "description": "Thresholds are 10 mbit,50 mbit,100 mbit",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 10 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "OutBound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "friendly_name" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "player_state" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"session_key\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"title\", \"friendly_name\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"username\"",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 1, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Streams" }
   ],
   "targets": [
    {
     "alias": "Direct Play Streams",
     "measurement": "Tautulli",
     "query": "SELECT count(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'current_stream_stats') AND $timeFilter",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    },
    {
     "alias": "Direct Streams",
     "measurement": "Tautulli",
     "query": "SELECT count(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'current_stream_stats') AND $timeFilter",
     "select": [
      [
       { "params": [ "direct_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    },
    {
     "alias": "Transcoding Streams",
     "measurement": "Tautulli",
     "query": "SELECT count(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'current_stream_stats') AND $timeFilter",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Stream Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_video_decision",
     "groupBy": [
      { "params": [ "video_decision" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Top Device Types This Month",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_device_type",
     "groupBy": [
      { "params": [ "device_type" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 1, "y": 20 },
   "yaxes": [
    { "format": "KBs", "label": "KB/s" }
   ],
   "targets": [
    {
     "alias": "LAN",
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "lan_bandwidth" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "WAN",
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Pipeline Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Missing TV Shows (Last 7 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 1, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  },
  {
   "title": "Missing Available Movies",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "titleSlug" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Missing_Available", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows on Today",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "downloaded" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "airsUTC" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Future" }
     ]
    }
   ]
  }
 ]
}