apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

  - name: InfluxDB-${INFLUXDB_DATABASE}
    orgId: 1

  - name: InfluxDB-Telegraf
    orgId: 1

  - name: InfluxDB-Proxmox
    orgId: 1

  - name: InfluxDB-Unifi
    orgId: 1

  - name: InfluxDB-UPS
    orgId: 1

  - name: InfluxDB-Odroid
    orgId: 1

  - name: InfluxDB-Varken
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false

  - name: InfluxDB-${INFLUXDB_DATABASE}
    type: influxdb
    access: proxy
    database: ${INFLUXDB_DATABASE}
    user: ${INFLUXDB_USERNAME}
    url: http://influxdb:8086
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}

  - name: InfluxDB-Telegraf
    type: influxdb
    access: proxy
    database: telegraf
    user: ${INFLUXDB_USERNAME}
    url: http://influxdb:8086
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}

  - name: InfluxDB-Proxmox
    type: influxdb
    access: proxy
    database: proxmox
    user: ${INFLUXDB_USERNAME}
    url: http://influxdb:8086
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}

  - name: InfluxDB-Odroid
    type: influxdb
    access: proxy
    database: odroid
    user: ${INFLUXDB_USERNAME}
    url: http://influxdb:8086
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}

  - name: InfluxDB-Varken
    type: influxdb
    access: proxy
    database: varken
    user: ${INFLUXDB_USERNAME}
    url: http://influxdb:8086
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}

  - name: InfluxDB-Unifi
    type: influxdb
    access: proxy
    database: unifi
    user: ${INFLUXDB_USERNAME}
    url: http://influxdb:8086
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}

  - name: InfluxDB-UPS
    type: influxdb
    access: proxy
    database: ups
    user: ${INFLUXDB_USERNAME}
    url: http://influxdb:8086
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}
